name: 'ci'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4+sha512.9df9cf27c91715646c7d675d1c9c8e41f6fce88246f1318c1aa6a1ed1aeb3c4f032fcdf4ba63cc69c4fe6d634279176b5358727d8f2cc1e65b65f43ce2f8bfb0
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Prepare environment
        run: |
          pnpm run prisma:setup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install Playwright Dependencies
        run: pnpm exec playwright install chromium --with-deps

      - name: Run vitest
        run: pnpm test

      - name: Run lint
        run: pnpm lint

      - name: Run typecheck
        run: pnpm typecheck
